use std::collections::HashMap;
use std::{env, fs, path::PathBuf};

use heck::ToSnakeCase;
use serde_json::Value;

#[derive(Clone)]
struct Op {
    method: String,
    path_template: String,
    operation_id: String,
    summary: String,
}

const FALLBACK_OPENAPI: &str = r#"{
  "openapi": "3.1.0",
  "info": {
    "title": "Timely API Docs",
    "version": "V1"
  },
  "paths": {},
  "components": {
    "schemas": {}
  }
}"#;
const OPENAPI_RELATIVE_PATH: &str = "../tmp/openapi/openapi.json";

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let spec_path = root.join(OPENAPI_RELATIVE_PATH);
    println!("cargo:rerun-if-changed={}", spec_path.display());
    println!("cargo:rerun-if-changed={}", root.join("build.rs").display());

    println!("cargo:rerun-if-env-changed=TIMELY_ALLOW_EMPTY_OPENAPI");
    println!("cargo:rerun-if-env-changed=PROFILE");

    let spec = match fs::read(&spec_path) {
        Ok(spec) => spec,
        Err(error) => {
            let profile = env::var("PROFILE").unwrap_or_else(|_| "release".to_string());
            let allow_empty = env::var("TIMELY_ALLOW_EMPTY_OPENAPI")
                .map(|value| value == "1")
                .unwrap_or(false)
                || profile == "debug";
            if !allow_empty {
                panic!(
                    "missing OpenAPI spec at {} ({error}). \
                     Run `ruby scripts/update-openapi.rb` or set TIMELY_ALLOW_EMPTY_OPENAPI=1 \
                     only for local bootstrap builds.",
                    spec_path.display()
                );
            }
            println!(
                "cargo:warning=missing {}; building with an empty embedded spec",
                spec_path.display()
            );
            FALLBACK_OPENAPI.as_bytes().to_vec()
        }
    };

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let openapi_out = out_dir.join("openapi.json");
    fs::write(&openapi_out, &spec).expect("write generated OpenAPI");

    let spec_value: Value = serde_json::from_slice(&spec).expect("parse OpenAPI JSON");
    let api_methods = generate_api_methods(&spec_value);
    fs::write(out_dir.join("api_methods.rs"), api_methods).expect("write api_methods.rs");
}

fn generate_api_methods(spec: &Value) -> String {
    let paths = spec
        .get("paths")
        .and_then(Value::as_object)
        .expect("OpenAPI paths");

    let mut ops = Vec::new();
    for (path_template, item) in paths {
        let Some(item) = item.as_object() else {
            continue;
        };
        for method in ["get", "post", "put", "patch", "delete"] {
            let Some(op) = item.get(method) else {
                continue;
            };
            if !op.is_object() {
                continue;
            }
            let operation_id = op
                .get("operationId")
                .and_then(Value::as_str)
                .map(str::to_string)
                .unwrap_or_else(|| generated_operation_id(method, path_template));
            let summary = op
                .get("summary")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string();
            ops.push(Op {
                method: method.to_uppercase(),
                path_template: path_template.clone(),
                operation_id,
                summary,
            });
        }
    }

    ops.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));

    let mut name_counts: HashMap<String, usize> = HashMap::new();
    let mut out = String::from(
        "// Generated by build.rs from OpenAPI — do not edit.\n\n\
#[allow(dead_code)]\n\
impl Api {\n",
    );

    for op in ops {
        let rust_name = allocate_rust_method_name(&op.operation_id, &mut name_counts);
        let path_params = path_param_names(&op.path_template);
        out.push_str(&emit_method(&rust_name, &op, &path_params));
    }
    out.push('}');
    out
}

fn allocate_rust_method_name(operation_id: &str, counts: &mut HashMap<String, usize>) -> String {
    let mut base = operation_id.to_snake_case();
    if base.is_empty() {
        base = "unnamed_operation".to_string();
    }
    if base.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        base = format!("op_{base}");
    }
    let n = counts.entry(base.clone()).or_insert(0);
    *n += 1;
    if *n == 1 { base } else { format!("{base}_{n}") }
}

fn generated_operation_id(method: &str, path: &str) -> String {
    let suffix = path
        .trim_matches('/')
        .replace('{', "by_")
        .replace('}', "")
        .replace(['/', '-'], "_")
        .replace('.', "_");
    format!("{method}_{suffix}")
}

fn path_param_names(path: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        let after = &rest[start + 1..];
        let end = after.find('}').expect("unclosed { in path");
        out.push(after[..end].to_string());
        rest = &after[end + 1..];
    }
    out
}

fn rust_param_ident(name: &str) -> String {
    if is_rust_keyword(name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "gen"
            | "union"
    )
}

fn escape_doc_line(s: &str) -> String {
    let one_line: String = s.lines().next().unwrap_or("").trim().to_string();
    one_line.replace('\\', "\\\\").replace("*/", "*\\/")
}

fn emit_method(rust_name: &str, op: &Op, path_params: &[String]) -> String {
    let doc_line = if op.summary.is_empty() {
        format!("{} {}", op.method, op.path_template)
    } else {
        format!(
            "{} {} — {}",
            op.method,
            op.path_template,
            escape_doc_line(&op.summary)
        )
    };
    let doc_attr = escape_doc_attr(&doc_line);
    let mut s = String::new();
    s.push_str(&format!("    #[doc = \"{doc_attr}\"]\n"));
    s.push_str(&format!("    pub async fn {rust_name}(\n"));
    s.push_str("        &self,\n");
    for p in path_params {
        let id = rust_param_ident(p);
        s.push_str(&format!("        {id}: &str,\n"));
    }
    s.push_str("        query: Vec<(String, String)>,\n");
    s.push_str("        body: Option<serde_json::Value>,\n");
    s.push_str("    ) -> anyhow::Result<serde_json::Value> {\n");
    if path_params.is_empty() {
        s.push_str(&format!(
            "        self.send(\"{}\", \"{}\", query, body).await\n",
            escape_rust_string(&op.method),
            escape_rust_string(&op.path_template)
        ));
    } else {
        s.push_str("        let mut params = std::collections::BTreeMap::new();\n");
        for p in path_params {
            let id = rust_param_ident(p);
            s.push_str(&format!(
                "        params.insert(\"{p}\".to_string(), {id}.to_string());\n"
            ));
        }
        let path_t = escape_rust_string(&op.path_template);
        s.push_str(&format!(
            "        let path = crate::util::fill_path_params(\"{path_t}\", &params)?;\n"
        ));
        s.push_str(&format!(
            "        self.send(\"{}\", &path, query, body).await\n",
            escape_rust_string(&op.method)
        ));
    }
    s.push_str("    }\n\n");
    s
}

fn escape_doc_attr(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("*/", "*\\/")
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
